### ISSUE TITLE
Zou je alle CSS netjes willen inspringen?

### ISSUE THREAD

**Issue by kriskuiper** [babicevl/website-frontend#8]
Opzich oogt het best netjes, dus ik maak me verder niet druk. Denk dat het wel helpt als je alles even netjes inspringt, dus als volgt:

```css
body {
  background-color: red;
  color: red;
}
```

https://github.com/babicevl/website-frontend/blob/eb42abd61eb1e644d7c955f2fdacea6fff24617e/styles/style.css#L6-L26
